HETHONGQUANLYQUANSO/Models/DonVi.cs
namespace HETHONGQUANLYQUANSO.Models
{
    public partial class DonVi
    {
        public DonVi()
        {
            BaoCaoQuanSos = new HashSet<BaoCaoQuanSo>();
            QuanNhans = new HashSet<QuanNhan>();
            ThongBaos = new HashSet<ThongBao>();
        }

        public string MaDonVi { get; set; } = null!;
        public string? TenDonVi { get; set; }
        public string? GhiChu { get; set; }

        public virtual ICollection<BaoCaoQuanSo> BaoCaoQuanSos { get; set; }
        public virtual ICollection<QuanNhan> QuanNhans { get; set; }
        public virtual ICollection<ThongBao> ThongBaos { get; set; }
    }
}

HETHONGQUANLYQUANSO/Controllers/DonViController.cs
using Microsoft.AspNetCore.Mvc;

namespace HETHONGQUANLYQUANSO.Controllers
{
    public class DonViController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Update()
        {
            return View();
        }
    }
}

HETHONGQUANLYQUANSO/ViewComponents/DonViViewComponent.cs
using Microsoft.AspNetCore.Mvc;
namespace HETHONGQUANLYQUANSO.ViewComponents
{
    public class DonViViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            // Logic của bạn ở đây
            return View();
        }
    }
}

HETHONGQUANLYQUANSO/ViewComponents/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace HETHONGQUANLYQUANSO.ViewComponents
{
    public class MenuViewComponent : ViewComponent

    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            // Logic của bạn ở đây
            return View();
        }

    }
}

HETHONGQUANLYQUANSO/Views/DonVi/Index.cshtml
@{
	Layout = "_Layout";
	ViewData["Title"] = "Insert";
}

@await Component.InvokeAsync("Menu")

HETHONGQUANLYQUANSO/Views/DonVi/Update.cshtml
@{
	Layout = "_Layout";
	ViewData["Title"] = "Update";
}
<div class="app" style="display: flex;">
	@await Component.InvokeAsync("Menu")
	<div class="card" style="width: 100%">
		<div class="card card-primary">
			<div class="card-header" style="background-color: #004400;">
				<h3 class="card-title">Cập nhật thông tin đơn vị</h3>
			</div>
			<!-- /.card-header -->
			<!-- form start -->
			<form>
				<div class="card-body">
					<div class="card-form" style="display: flex; justify-content: space-between;">
						<div class="form-group" style="flex: 1;margin-right: 20px">
							<label for="exampleInputEmail1">Mã đơn vị</label>
							<input type="text" class="form-control" id="exampleInputEmail1" placeholder="Nhập mã đơn vị">
						</div>
						<div class="form-group" style="flex: 1; margin-left: 20px;">
							<label for="exampleInputPassword1">Tên đơn vị</label>
							<input type="text" class="form-control" id="exampleInputPassword1" placeholder="Nhập tên đơn vị">
						</div>
					</div>
				</div>
				<div class="group-btn" style="display: flex; justify-content: space-between;">
					<button type="button" class="btn btn-block btn-success btn-lg" style="width: 150px; height: 50px; margin-left: 20px; margin-bottom: 0;">Thêm</button>
					<button type="button" class="btn btn-block btn-warning btn-lg" style="width: 150px; height: 50px; margin-bottom: 20px;">Sửa</button>
					<button type="button" class="btn btn-block btn-danger btn-lg" style="width: 150px; height: 50px; margin-right: 20px; margin-bottom: 20px;">Xóa</button>
				</div>
				<!-- /.card-body -->
			</form>
		</div>
		@await Component.InvokeAsync("DonVi")
	</div>
</div>